import { useMemo } from 'react';
import { buildAppOverlaysModel } from '@/components/app/overlays/buildAppOverlaysModel';
import { buildSettingsDialogModel } from '@/components/app/dialogs/buildSettingsDialogModel';
import { buildAppDialogsModel } from '@/components/app/dialogs/buildAppDialogsModel';
import type { AppViewModelContext } from './useAppViewModels.shared';

// 覆盖层、设置弹窗与通用对话框的 view model 组装
export function useAppOverlayDialogViewModels(core: AppViewModelContext) {
    const {
        currentView,
        isOverlayVisible,
        isSearchOpen,
        topOverlay,
        overlayStack,
        theme,
        isDaylight,
        closeSearchView,
        handleSearchOverlaySubmit,
        handleSearchLoadMore,
        handleSearchResultPlay,
        handleSearchResultArtistSelect,
        handleSearchResultAlbumSelect,
        popOverlay,
        playSong,
        playOnlineQueueFromStart,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        user,
        playlists,
        refreshUserData,
        isDev,
        isDevDebugOverlayVisible,
        devDebugSnapshot,
        currentTime,
        lyricCurrentTime,
        currentSong,
        playerState,
        duration,
        effectiveLoopMode,
        audioSrc,
        canToggleCurrentPlayback,
        isNowPlayingControlDisabled,
        lyrics,
        activePlaybackContext,
        stageActiveEntryKind,
        syncStageLyricsClock,
        stageLyricsClockRef,
        setPlayerState,
        togglePlay,
        toggleLoop,
        navigateToPlayer,
        isPlayerChromeHidden,
        shouldHidePlayerProgressBar,
        seekMainAudio,
        publishStagePlayerPlaybackUpdate,
        t,
        settingsModalState,
        closeSettings,
        themeController,
        themeParkSeedTheme,
        handleToggleNavidromeEnabled,
        loadCurrentSongLyricPreview,
        handleSaveLyricFilterPattern,
        stageStatus,
        stageSource,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        handleAudioOutputDeviceChange,
        toggleTransparentModeWithHandoff,
        desktopLyricsStatus,
        toggleDesktopLyrics,
        setDesktopLyricsLocked,
        statusMsg,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        handleUnavailableReplacementConfirm,
    } = core;

    const appOverlaysModel = useMemo(() => buildAppOverlaysModel({
        currentView,
        isOverlayVisible,
        isSearchOpen,
        topOverlay,
        overlayStack,
        theme,
        isDaylight,
        closeSearchView,
        handleSearchOverlaySubmit,
        handleSearchLoadMore,
        handleSearchResultPlay,
        handleSearchResultArtistSelect,
        handleSearchResultAlbumSelect,
        popOverlay,
        playSong,
        playOnlineQueueFromStart,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        handleAlbumSelect: handleUnifiedAlbumSelect,
        handleArtistSelect: handleUnifiedArtistSelect,
        userId: user?.userId,
        playlists,
        refreshUserData,
        isDev,
        isDevDebugOverlayVisible,
        devDebugSnapshot,
        currentTime,
        lyricCurrentTime,
        currentSong,
        playerState,
        duration,
        effectiveLoopMode,
        audioSrc,
        canToggleCurrentPlayback,
        isNowPlayingControlDisabled,
        lyrics,
        activePlaybackContext,
        stageActiveEntryKind,
        syncStageLyricsClock,
        stageLyricsClockRef,
        setPlayerState,
        togglePlay,
        toggleLoop,
        navigateToPlayer,
        isPlayerChromeHidden,
        shouldHidePlayerProgressBar,
        onSeekMainAudio: seekMainAudio,
        onStagePlayerSeek: publishStagePlayerPlaybackUpdate,
        noTrackText: t('ui.noTrack'),
    }), [
        activePlaybackContext,
        addNeteaseSongToQueue,
        addNeteaseSongsToQueue,
        audioSrc,
        canToggleCurrentPlayback,
        closeSearchView,
        currentSong,
        currentTime,
        currentView,
        devDebugSnapshot,
        duration,
        effectiveLoopMode,
        handleSearchLoadMore,
        handleSearchOverlaySubmit,
        handleSearchResultAlbumSelect,
        handleSearchResultArtistSelect,
        handleSearchResultPlay,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        isDaylight,
        isDev,
        isDevDebugOverlayVisible,
        isNowPlayingControlDisabled,
        isOverlayVisible,
        isPlayerChromeHidden,
        isSearchOpen,
        lyrics,
        lyricCurrentTime,
        navigateToPlayer,
        overlayStack,
        playerState,
        playlists,
        playOnlineQueueFromStart,
        playSong,
        popOverlay,
        publishStagePlayerPlaybackUpdate,
        refreshUserData,
        seekMainAudio,
        setPlayerState,
        shouldHidePlayerProgressBar,
        stageActiveEntryKind,
        stageLyricsClockRef,
        syncStageLyricsClock,
        theme,
        toggleLoop,
        togglePlay,
        topOverlay,
        t,
        user?.userId,
    ]);

    const settingsDialog = useMemo(() => buildSettingsDialogModel({
        state: settingsModalState,
        onClose: closeSettings,
        themeController,
        themeParkInitialTheme: themeParkSeedTheme,
        onToggleNavidrome: handleToggleNavidromeEnabled,
        currentSongTitle: currentSong?.name || null,
        loadLyricFilterPreview: loadCurrentSongLyricPreview,
        onSaveLyricFilterPattern: handleSaveLyricFilterPattern,
        stageStatus,
        stageSource,
        activePlaybackContext,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        onAudioOutputDeviceChange: handleAudioOutputDeviceChange,
        onToggleTransparentPlayerBackground: toggleTransparentModeWithHandoff,
        desktopLyricsStatus,
        onToggleDesktopLyrics: toggleDesktopLyrics,
        onSetDesktopLyricsLocked: setDesktopLyricsLocked,
    }), [
        activePlaybackContext,
        clearPersistedStagePlaybackCache,
        clearStagePlaybackSession,
        closeSettings,
        currentSong?.name,
        desktopLyricsStatus,
        handleAudioOutputDeviceChange,
        handleSaveLyricFilterPattern,
        handleToggleNavidromeEnabled,
        leaveStagePlayback,
        loadCurrentSongLyricPreview,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        setDesktopLyricsLocked,
        settingsModalState,
        setStageStatus,
        stageSource,
        stageStatus,
        themeController,
        themeParkSeedTheme,
        toggleDesktopLyrics,
        toggleTransparentModeWithHandoff,
    ]);

    const appDialogsModel = useMemo(() => buildAppDialogsModel({
        statusMsg,
        isDaylight,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        currentSong,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        handleUnavailableReplacementConfirm,
        settingsDialog,
    }), [
        currentSong,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        handleUnavailableReplacementConfirm,
        isDaylight,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        settingsDialog,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        statusMsg,
    ]);

    return {
        appDialogsModel,
        appOverlaysModel,
        settingsDialog,
        showLyricMatchModal,
    };
}
