import { useMemo } from 'react';
import { buildAppOverlaysModel } from '@/components/app/overlays/buildAppOverlaysModel';
import { buildSettingsDialogModel } from '@/components/app/dialogs/buildSettingsDialogModel';
import { buildAppDialogsModel } from '@/components/app/dialogs/buildAppDialogsModel';
import { getVisualizerModeLabel as resolveVisualizerModeLabel } from '@/components/visualizer/registry';
import { isLocalPlaybackSong, isNavidromePlaybackSong } from '@/utils/appPlaybackGuards';
import type { AppViewModelContext } from './useAppViewModels.shared';
import type { AudioQuality } from '@/stores/useSettingsUiStore';

// 覆盖层、设置弹窗与通用对话框的 view model 组装
export function useAppOverlayDialogViewModels(core: AppViewModelContext) {
    const {
        currentView,
        isOverlayVisible,
        isSearchOpen,
        topOverlay,
        overlayStack,
        theme,
        isDaylight,
        closeSearchView,
        handleSearchOverlaySubmit,
        handleSearchLoadMore,
        handleSearchResultPlay,
        handleSearchResultArtistSelect,
        handleSearchResultAlbumSelect,
        popOverlay,
        playSong,
        playOnlineQueueFromStart,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        user,
        playlists,
        refreshUserData,
        isDev,
        isDevDebugOverlayVisible,
        devDebugSnapshot,
        currentTime,
        lyricCurrentTime,
        currentSong,
        playerState,
        duration,
        effectiveLoopMode,
        playerLyricsVisible,
        handleTogglePlayerLyricsVisible,
        playQueue,
        coverUrl,
        audioSrc,
        canToggleCurrentPlayback,
        isNowPlayingControlDisabled,
        lyrics,
        activePlaybackContext,
        stageActiveEntryKind,
        syncStageLyricsClock,
        stageLyricsClockRef,
        setPlayerState,
        togglePlay,
        toggleLoop,
        handlePrevTrack,
        handleNextTrack,
        navigateToPlayer,
        navigateToHome,
        isPlayerChromeHidden,
        shouldHidePlayerProgressBar,
        seekMainAudio,
        publishStagePlayerPlaybackUpdate,
        isImmersiveFullscreen,
        toggleImmersiveFullscreen,
        exitWindowFullscreen,
        setIsPlayerChromeHidden,
        audioQuality,
        setAudioQuality,
        changeAudioQuality,
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        handleSetVisualizerBackgroundMode,
        handleSetInteractive3dSceneTuning,
        visualizerMode,
        handleSetVisualizerMode,
        onApplyLyricColorPreset,
        t,
        settingsModalState,
        closeSettings,
        themeController,
        themeParkSeedTheme,
        handleToggleNavidromeEnabled,
        loadCurrentSongLyricPreview,
        handleSaveLyricFilterPattern,
        stageStatus,
        stageSource,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        handleAudioOutputDeviceChange,
        toggleTransparentModeWithHandoff,
        desktopLyricsStatus,
        toggleDesktopLyrics,
        setDesktopLyricsLocked,
        statusMsg,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        handleUnavailableReplacementConfirm,
    } = core;

    const appOverlaysModel = useMemo(() => buildAppOverlaysModel({
        currentView,
        isOverlayVisible,
        isSearchOpen,
        topOverlay,
        overlayStack,
        theme,
        isDaylight,
        closeSearchView,
        handleSearchOverlaySubmit,
        handleSearchLoadMore,
        handleSearchResultPlay,
        handleSearchResultArtistSelect,
        handleSearchResultAlbumSelect,
        popOverlay,
        playSong,
        playOnlineQueueFromStart,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        handleAlbumSelect: handleUnifiedAlbumSelect,
        handleArtistSelect: handleUnifiedArtistSelect,
        userId: user?.userId,
        playlists,
        refreshUserData,
        isDev,
        isDevDebugOverlayVisible,
        devDebugSnapshot,
        currentTime,
        lyricCurrentTime,
        currentSong,
        playerState,
        duration,
        effectiveLoopMode,
        playerLyricsVisible,
        playQueueLength: playQueue.length,
        audioSrc,
        canToggleCurrentPlayback,
        isNowPlayingControlDisabled,
        lyrics,
        activePlaybackContext,
        stageActiveEntryKind,
        syncStageLyricsClock,
        stageLyricsClockRef,
        setPlayerState,
        togglePlay,
        toggleLoop,
        onPrevTrack: handlePrevTrack,
        onNextTrack: handleNextTrack,
        onTogglePlayerLyricsVisible: () => {
            handleTogglePlayerLyricsVisible(!playerLyricsVisible);
        },
        navigateToPlayer,
        navigateToHome: () => {
            setIsPlayerChromeHidden(false);
            exitWindowFullscreen();
            navigateToHome();
        },
        isPlayerChromeHidden,
        shouldHidePlayerProgressBar,
        onSeekMainAudio: seekMainAudio,
        onStagePlayerSeek: publishStagePlayerPlaybackUpdate,
        noTrackText: t('ui.noTrack'),
        showLyricsLabel: t('player.showLyrics'),
        hideLyricsLabel: t('player.hideLyrics'),
        listeningModeLabel: t('player.listeningMode'),
        backToPlaylistLabel: t('player.backToPlaylist'),
        previousTrackLabel: t('player.previousTrack'),
        nextTrackLabel: t('player.nextTrack'),
        playLabel: t('player.play'),
        pauseLabel: t('player.pause'),
        loopOffLabel: t('player.loopOff'),
        loopListLabel: t('player.loopList'),
        loopOneLabel: t('player.loopOne'),
        isImmersiveFullscreen,
        onToggleImmersiveFullscreen: () => {
            toggleImmersiveFullscreen();
        },
        enterFullscreenLabel: t('player.enterFullscreen'),
        exitFullscreenLabel: t('player.exitFullscreen'),
        onRevealLyricsInPlayer: navigateToPlayer,
        coverUrl,
        audioQuality,
        canChangeAudioQuality: Boolean(
            currentSong
            && !isNowPlayingControlDisabled
            && !isLocalPlaybackSong(currentSong)
            && !isNavidromePlaybackSong(currentSong),
        ),
        onAudioQualityChange: (quality: AudioQuality) => {
            if (quality === audioQuality) return;
            setAudioQuality(quality);
            changeAudioQuality(quality);
        },
        qualityExhighLabel: t('account.qualityExhigh'),
        qualityLosslessLabel: t('account.qualityLossless'),
        qualityHiresLabel: t('account.qualityHires'),
        audioQualityLabel: t('player.audioQuality') || t('account.audioQuality'),
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        onVisualizerBackgroundModeChange: handleSetVisualizerBackgroundMode,
        onInteractive3dSceneTuningChange: handleSetInteractive3dSceneTuning,
        visualizerMode,
        onVisualizerModeChange: handleSetVisualizerMode,
        onApplyLyricColorPreset,
        backgroundMenuLabel: t('player.backgroundMenu') || t('ui.playerPageBackground') || 'Background',
        backgroundModeInteractive3dLabel: t('options.visualizerBackgroundModeInteractive3d') || '3D',
        backgroundModeCommonLabel: t('options.visualizerBackgroundModeCommon') || 'Common',
        backgroundModeMonetLabel: t('options.visualizerBackgroundModeMonet') || 'Monet',
        backgroundPresetSectionLabel: t('options.mineradioVisualPreset') || '3D style',
        lyricsStyleSectionLabel: t('player.lyricsStyleSection') || t('ui.lyricsAnimationStyle') || 'Lyric style',
        lyricColorSectionLabel: t('player.lyricColorSection') || t('options.lyricColorPresetTitle') || 'Lyric colors',
        getBackgroundPresetLabel: (preset) => t(`options.mineradioPreset.${preset}`),
        getVisualizerModeLabel: (mode) => resolveVisualizerModeLabel(mode, t),
    }), [
        activePlaybackContext,
        addNeteaseSongToQueue,
        addNeteaseSongsToQueue,
        audioQuality,
        audioSrc,
        canToggleCurrentPlayback,
        changeAudioQuality,
        closeSearchView,
        coverUrl,
        currentSong,
        currentTime,
        currentView,
        devDebugSnapshot,
        duration,
        effectiveLoopMode,
        handleNextTrack,
        handlePrevTrack,
        handleSearchLoadMore,
        handleSearchOverlaySubmit,
        handleSearchResultAlbumSelect,
        handleSearchResultArtistSelect,
        handleSearchResultPlay,
        handleTogglePlayerLyricsVisible,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        isDaylight,
        isDev,
        isDevDebugOverlayVisible,
        isNowPlayingControlDisabled,
        isOverlayVisible,
        isPlayerChromeHidden,
        isImmersiveFullscreen,
        isSearchOpen,
        lyrics,
        lyricCurrentTime,
        navigateToPlayer,
        navigateToHome,
        setIsPlayerChromeHidden,
        exitWindowFullscreen,
        overlayStack,
        playerLyricsVisible,
        playerState,
        playlists,
        playOnlineQueueFromStart,
        playQueue.length,
        playSong,
        popOverlay,
        publishStagePlayerPlaybackUpdate,
        refreshUserData,
        seekMainAudio,
        setAudioQuality,
        setPlayerState,
        shouldHidePlayerProgressBar,
        stageActiveEntryKind,
        stageLyricsClockRef,
        syncStageLyricsClock,
        theme,
        toggleImmersiveFullscreen,
        toggleLoop,
        togglePlay,
        topOverlay,
        t,
        user?.userId,
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        handleSetVisualizerBackgroundMode,
        handleSetInteractive3dSceneTuning,
        visualizerMode,
        handleSetVisualizerMode,
        onApplyLyricColorPreset,
    ]);

    const settingsDialog = useMemo(() => buildSettingsDialogModel({
        state: settingsModalState,
        onClose: closeSettings,
        themeController,
        themeParkInitialTheme: themeParkSeedTheme,
        onToggleNavidrome: handleToggleNavidromeEnabled,
        currentSongTitle: currentSong?.name || null,
        currentCoverUrl: coverUrl,
        loadLyricFilterPreview: loadCurrentSongLyricPreview,
        onSaveLyricFilterPattern: handleSaveLyricFilterPattern,
        stageStatus,
        stageSource,
        activePlaybackContext,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        onAudioOutputDeviceChange: handleAudioOutputDeviceChange,
        onToggleTransparentPlayerBackground: toggleTransparentModeWithHandoff,
        desktopLyricsStatus,
        onToggleDesktopLyrics: toggleDesktopLyrics,
        onSetDesktopLyricsLocked: setDesktopLyricsLocked,
    }), [
        activePlaybackContext,
        clearPersistedStagePlaybackCache,
        clearStagePlaybackSession,
        closeSettings,
        coverUrl,
        currentSong?.name,
        desktopLyricsStatus,
        handleAudioOutputDeviceChange,
        handleSaveLyricFilterPattern,
        handleToggleNavidromeEnabled,
        leaveStagePlayback,
        loadCurrentSongLyricPreview,
        loadStageSessionIntoPlayback,
        nowPlayingConnectionStatus,
        obsBrowserSourceStatus,
        refreshObsBrowserSourceStatus,
        setDesktopLyricsLocked,
        settingsModalState,
        setStageStatus,
        stageSource,
        stageStatus,
        themeController,
        themeParkSeedTheme,
        toggleDesktopLyrics,
        toggleTransparentModeWithHandoff,
    ]);

    const appDialogsModel = useMemo(() => buildAppDialogsModel({
        statusMsg,
        isDaylight,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        currentSong,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        handleUnavailableReplacementConfirm,
        settingsDialog,
    }), [
        currentSong,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        handleUnavailableReplacementConfirm,
        isDaylight,
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        settingsDialog,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        statusMsg,
    ]);

    return {
        appDialogsModel,
        appOverlaysModel,
        settingsDialog,
        showLyricMatchModal,
    };
}
