import { useMemo } from 'react';
import { buildPlaylistShelfItems } from '@/components/visualizer/geometric/shelf/buildPlaylistShelfItems';
import { createLyricFilterPatternSaver } from '@/components/app/home/createLyricFilterPatternSaver';
import { createLocalLibraryNavigation } from '@/components/app/navigation/createLocalLibraryNavigation';
import { createNavidromeNavigation } from '@/components/app/navigation/createNavidromeNavigation';
import { createPanelNavigation } from '@/components/app/navigation/createPanelNavigation';
import { createQueueMutations } from '@/components/app/player-panel/createQueueMutations';
import { LOCAL_MUSIC_UPDATED_EVENT } from '@/components/app/root/appConstants';
import { useLibraryPlaybackController } from '@/hooks/useLibraryPlaybackController';
import { usePlaybackQueueController } from '@/hooks/usePlaybackQueueController';
import { usePlaybackUiEffects } from '@/hooks/usePlaybackUiEffects';
import { useSessionRestoreController } from '@/hooks/useSessionRestoreController';
import type { AppControllerCoreResult } from './useAppController.types';

export function useAppControllerLibrary(core: AppControllerCoreResult) {
    const {
        activePlaybackContext,
        audioQuality,
        audioRef,
        blobUrlRef,
        clearPersistedStagePlaybackCache,
        currentOnlineAudioUrlFetchedAtRef,
        currentSong,
        currentSongRef,
        currentTime,
        currentView,
        handleAlbumSelect: navigateToNeteaseAlbum,
        handleArtistSelect: navigateToNeteaseArtist,
        handleSetLyricFilterPattern,
        hideSearchOverlay,
        interruptStagePlaybackForMainTransition,
        isFmMode,
        isNowPlayingStageActive,
        isPanelOpen,
        lastAudioRecoverySourceRef,
        likedSongIds,
        loadMoreSearchResults,
        loopMode,
        lyrics,
        mainPlaybackSnapshotRef,
        navigateDirectHome,
        navigateToPlayer,
        navigateToSearch,
        panelTab,
        pendingResumeTimeRef,
        pendingUnavailableSkipIntervalRef,
        pendingUnavailableSkipTimerRef,
        persistLastPlaybackCache,
        playQueue,
        playbackAutoSkipCountRef,
        playbackRequestIdRef,
        playerState,
        playlists,
        queueAddBehavior,
        restoreCachedThemeForSong,
        searchQuery,
        searchSourceTab,
        setAudioSrc,
        setCachedCoverUrl,
        setCurrentLineIndex,
        setCurrentSong,
        setDuration,
        setHomeViewTab,
        setIsFmMode,
        setIsLyricsLoading,
        setIsPanelOpen,
        setLikedSongIds,
        setLocalMusicState,
        setLyrics,
        setPanelTab,
        setPendingNavidromeSelection,
        setPlayQueue,
        setPlayerState,
        setStarredNavidromeSongIds,
        setStatusMsg,
        shouldAutoPlay,
        starredNavidromeSongIds,
        statusMsg,
        submitSearch,
        t,
        updateCacheSize,
        user,
        volumePreviewFrameRef,
        windowPlaybackHandoffRestoreStatus,
    } = core;

    const { openCurrentNavidromeAlbum, openCurrentNavidromeArtist } = createNavidromeNavigation({
        currentSong,
        setPendingNavidromeSelection,
        setHomeViewTab,
        navigateDirectHome,
    });

    const { handleDirectHomeFromPanel } = createPanelNavigation(navigateDirectHome);

    const {
        localSongs,
        localPlaylists,
        showLyricMatchModal,
        setShowLyricMatchModal,
        showNaviLyricMatchModal,
        setShowNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        setShowOnlineLyricMatchModal,
        loadLocalSongs,
        loadLocalPlaylists,
        onRefreshLocalSongs,
        isLocalSongLiked,
        saveCurrentQueueAsLocalPlaylist,
        addCurrentSongToLocalPlaylist,
        createCurrentLocalPlaylist,
        addCurrentSongToNeteasePlaylist,
        addCurrentSongToNavidromePlaylist,
        createCurrentNavidromePlaylist,
        loadCurrentSongLyricPreview,
        handleLocalQueueAdd,
        onPlayLocalSong,
        onPlayNavidromeSong,
        onMatchNavidromeSong,
        handleUpdateLocalLyrics,
        handleChangeLyricsSource,
        handleManualMatchOnline,
        handleImportOnlineLyrics,
        handleChangeOnlineLyricsSource,
        handleMatchOnlineLyrics,
        handleLyricMatchComplete,
        handleNaviLyricMatchComplete,
        handleOnlineLyricMatchComplete,
        handleClearOnlineLyricsState,
        handleHomeMatchSong,
        handleAutoMatchBestLyricForCurrentSong,
        handleLike,
    } = useLibraryPlaybackController({
        t: (key, fallback) => t(key, fallback ?? ''),
        audioQuality,
        queueAddBehavior,
        currentSong,
        lyrics,
        playQueue,
        likedSongIds,
        userId: user?.userId,
        currentTime,
        setCurrentSong,
        setLyrics,
        setCachedCoverUrl,
        setAudioSrc,
        setPlayQueue,
        setPlayerState,
        setCurrentLineIndex,
        setDuration,
        setIsLyricsLoading,
        setStatusMsg,
        setIsPanelOpen,
        setLikedSongIds,
        starredNavidromeSongIds,
        setStarredNavidromeSongIds,
        navigateToPlayer,
        persistLastPlaybackCache,
        restoreCachedThemeForSong,
        interruptStagePlaybackForMainTransition,
        blobUrlRef,
        shouldAutoPlayRef: shouldAutoPlay,
        currentSongRef,
        currentOnlineAudioUrlFetchedAtRef,
    });

    const playlistShelfItems = useMemo(
        () => buildPlaylistShelfItems({
            playQueue,
            localPlaylists,
            neteasePlaylists: playlists,
        }),
        [localPlaylists, playQueue, playlists],
    );

    useSessionRestoreController({
        audioQuality,
        userId: user?.userId,
        blobUrlRef,
        currentOnlineAudioUrlFetchedAtRef,
        setCurrentSong,
        setPlayQueue,
        setCachedCoverUrl,
        setAudioSrc,
        setLyrics,
        setStatusMsg,
        restoreCachedThemeForSong,
        persistLastPlaybackCache,
        clearPersistedStagePlaybackCache,
        loadLocalSongs,
        loadLocalPlaylists,
        canRestoreSession: windowPlaybackHandoffRestoreStatus === 'none',
    });

    const {
        openCurrentLocalAlbum,
        openCurrentLocalArtist,
        openLocalAlbumByName,
        openLocalArtistByName,
    } = createLocalLibraryNavigation({
        currentView,
        currentSong,
        localSongs,
        setHomeViewTab,
        setLocalMusicState,
        navigateDirectHome,
    });

    const handleSaveLyricFilterPattern = createLyricFilterPatternSaver({
        handleSetLyricFilterPattern,
        loadCurrentSongLyricPreview,
        setLyrics,
        setCurrentLineIndex,
        setStatusMsg,
    });

    const { addNavidromeSongsToQueue } = createQueueMutations({
        currentSong,
        playQueue,
        setPlayQueue,
        persistLastPlaybackCache,
        setStatusMsg,
        t: key => t(key),
        queueAddBehavior,
    });

    const {
        pendingUnavailableReplacement,
        setPendingUnavailableReplacement,
        clearPendingUnavailableSkip,
        addNeteaseSongToQueue,
        addNeteaseSongsToQueue,
        playSong,
        playOnlineQueueFromStart,
        handleQueueAddAndPlay,
        handleSearchOverlaySubmit,
        handleSearchLoadMore,
        handleSearchResultPlay,
        handleUnavailableReplacementConfirm,
        handleSearchResultArtistSelect,
        handleSearchResultAlbumSelect,
        handleNextTrack,
        handlePrevTrack,
        skipAfterPlaybackFailure,
        handleStageExternalPlayRequest,
        shuffleQueue,
    } = usePlaybackQueueController({
        t,
        audioQuality,
        activePlaybackContext,
        currentSong,
        playQueue,
        playerState,
        loopMode,
        isFmMode,
        isNowPlayingStageActive,
        queueAddBehavior,
        searchQuery,
        searchSourceTab,
        localSongs,
        userId: user?.userId,
        currentTime,
        setCurrentSong,
        setLyrics,
        setCachedCoverUrl,
        setAudioSrc,
        setPlayQueue,
        setPlayerState,
        setCurrentLineIndex,
        setDuration,
        setIsLyricsLoading,
        setStatusMsg,
        setIsFmMode,
        setPanelTab,
        setIsPanelOpen,
        navigateToPlayer,
        navigateToSearch,
        hideSearchOverlay,
        setHomeViewTab,
        setPendingNavidromeSelection,
        handleArtistSelect: navigateToNeteaseArtist,
        handleAlbumSelect: navigateToNeteaseAlbum,
        openLocalArtistByName,
        openLocalAlbumByName,
        persistLastPlaybackCache,
        restoreCachedThemeForSong,
        interruptStagePlaybackForMainTransition,
        onPlayLocalSong,
        onPlayNavidromeSong,
        searchDeps: {
            submitSearch,
            loadMoreSearchResults,
        },
        audioRef,
        blobUrlRef,
        shouldAutoPlayRef: shouldAutoPlay,
        currentSongRef,
        mainPlaybackSnapshotRef,
        playbackRequestIdRef,
        playbackAutoSkipCountRef,
        pendingUnavailableSkipTimerRef,
        pendingUnavailableSkipIntervalRef,
        pendingResumeTimeRef,
        currentOnlineAudioUrlFetchedAtRef,
        lastAudioRecoverySourceRef,
    });

    usePlaybackUiEffects({
        statusMsg,
        setStatusMsg,
        isPanelOpen,
        panelTab,
        updateCacheSize,
        loadLocalSongs,
        loadLocalPlaylists,
        localMusicUpdatedEvent: LOCAL_MUSIC_UPDATED_EVENT,
        blobUrlRef,
        volumePreviewFrameRef,
        onClearPendingUnavailableSkip: clearPendingUnavailableSkip,
    });

    return {
        addCurrentSongToLocalPlaylist,
        addCurrentSongToNavidromePlaylist,
        addCurrentSongToNeteasePlaylist,
        addNavidromeSongsToQueue,
        addNeteaseSongToQueue,
        addNeteaseSongsToQueue,
        createCurrentLocalPlaylist,
        createCurrentNavidromePlaylist,
        handleAutoMatchBestLyricForCurrentSong,
        handleChangeLyricsSource,
        handleChangeOnlineLyricsSource,
        handleClearOnlineLyricsState,
        handleDirectHomeFromPanel,
        handleHomeMatchSong,
        handleImportOnlineLyrics,
        handleLike,
        handleLocalQueueAdd,
        handleLyricMatchComplete,
        handleManualMatchOnline,
        handleMatchOnlineLyrics,
        handleNaviLyricMatchComplete,
        handleNextTrack,
        handleOnlineLyricMatchComplete,
        handlePrevTrack,
        handleQueueAddAndPlay,
        handleSaveLyricFilterPattern,
        handleSearchLoadMore,
        handleSearchOverlaySubmit,
        handleSearchResultAlbumSelect,
        handleSearchResultArtistSelect,
        handleSearchResultPlay,
        handleStageExternalPlayRequest,
        handleUnavailableReplacementConfirm,
        handleUpdateLocalLyrics,
        isLocalSongLiked,
        loadCurrentSongLyricPreview,
        localSongs,
        onMatchNavidromeSong,
        onPlayLocalSong,
        onPlayNavidromeSong,
        onRefreshLocalSongs,
        openCurrentLocalAlbum,
        openCurrentLocalArtist,
        openCurrentNavidromeAlbum,
        openCurrentNavidromeArtist,
        openLocalAlbumByName,
        openLocalArtistByName,
        pendingUnavailableReplacement,
        playOnlineQueueFromStart,
        playSong,
        playlistShelfItems,
        saveCurrentQueueAsLocalPlaylist,
        setPendingUnavailableReplacement,
        setShowLyricMatchModal,
        setShowNaviLyricMatchModal,
        setShowOnlineLyricMatchModal,
        showLyricMatchModal,
        showNaviLyricMatchModal,
        showOnlineLyricMatchModal,
        shuffleQueue,
        skipAfterPlaybackFailure,
    };
}
