import { useMemo } from 'react';
import { buildHomeModel } from '@/components/app/home/buildHomeModel';
import { buildPlayerPanelModel } from '@/components/app/player-panel/buildPlayerPanelModel';
import { createPlayerPanelCollectionNavigation } from '@/components/app/player-panel/createPlayerPanelCollectionNavigation';
import { createCopySongInfoSuccessHandler } from '@/components/app/dialogs/createCopySongInfoSuccessHandler';
import { DEFAULT_THEME, DAYLIGHT_THEME } from '@/components/app/root/appConstants';
import { isLocalPlaybackSong, isNavidromePlaybackSong, resolveNavidromePlaybackCarrier } from '@/utils/appPlaybackGuards';
import type { AppViewModelContext } from './useAppViewModels.shared';

// Home 与 PlayerPanel 区域的 view model 组装
export function useAppHomeAndPanelViewModels(core: AppViewModelContext) {
    const {
        playSong,
        navigateToPlayer,
        refreshUserData,
        user,
        playlists,
        cloudPlaylist,
        favoriteAlbums,
        isFavoriteAlbumsLoading,
        favoriteAlbumsLoadFailed,
        currentSong,
        playerState,
        handlePlaylistSelect,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        focusedPlaylistIndex,
        setFocusedPlaylistIndex,
        focusedFavoriteAlbumIndex,
        setFocusedFavoriteAlbumIndex,
        focusedRadioIndex,
        setFocusedRadioIndex,
        openSettings,
        navigateToSearch,
        openLocalAlbumByName,
        openLocalArtistByName,
        localSongs,
        localPlaylists,
        onRefreshLocalSongs,
        onPlayLocalSong,
        handleLocalQueueAdd,
        localMusicState,
        setLocalMusicState,
        handleHomeMatchSong,
        onPlayNavidromeSong,
        addNavidromeSongsToQueue,
        onMatchNavidromeSong,
        navidromeFocusedAlbumIndex,
        setNavidromeFocusedAlbumIndex,
        pendingNavidromeSelection,
        setPendingNavidromeSelection,
        stageSource,
        activePlaybackContext,
        openStagePlayer,
        stageStatus,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        theme,
        navidromeEnabled,
        playOnlineQueueFromStart,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        isPanelOpen,
        setIsPanelOpen,
        panelTab,
        setPanelTab,
        navigateToHome,
        handleDirectHomeFromPanel,
        coverUrl,
        handlePlayerPanelAlbumSelect,
        handlePlayerPanelArtistSelect,
        effectiveLoopMode,
        toggleLoop,
        handleLike,
        likedSongIds,
        starredNavidromeSongIds,
        isLocalSongLiked,
        generateCurrentSongTheme,
        activateCurrentSmartTheme,
        isGeneratingTheme,
        lyrics,
        canGenerateAITheme,
        setTheme,
        bgMode,
        handleBgModeChange,
        hasCustomTheme,
        themeSourceModel,
        handleResetTheme,
        visualizerMode,
        handleSetVisualizerMode,
        handleManualMatchOnline,
        handleUpdateLocalLyrics,
        handleChangeLyricsSource,
        handleImportOnlineLyrics,
        handleChangeOnlineLyricsSource,
        handleMatchOnlineLyrics,
        handleClearOnlineLyricsState,
        lyricTimelineOffsetMs,
        setLyricTimelineOffsetMs,
        replayGainMode,
        handleChangeReplayGainMode,
        isFmMode,
        handleFmTrash,
        handleNextTrack,
        handlePrevTrack,
        togglePlay,
        volume,
        isMuted,
        handlePreviewVolume,
        handleSetVolume,
        handleToggleMute,
        showOpenPanelCloseButton,
        isPlayerChromeHidden,
        shouldHidePlayerProgressBar,
        shouldHidePlayerRightPanelButton,
        isNowPlayingControlDisabled,
        commandPalette,
        playQueue,
        queueScrollRef,
        shuffleQueue,
        saveCurrentQueueAsLocalPlaylist,
        addCurrentSongToLocalPlaylist,
        createCurrentLocalPlaylist,
        addCurrentSongToNeteasePlaylist,
        addCurrentSongToNavidromePlaylist,
        createCurrentNavidromePlaylist,
        openCurrentLocalAlbum,
        openCurrentLocalArtist,
        openCurrentNavidromeAlbum,
        openCurrentNavidromeArtist,
        setStatusMsg,
        t,
        handleLogout,
        audioQuality,
        setAudioQuality,
        cacheSize,
        handleClearCache,
        handleSyncData,
        isSyncing,
        useCoverColorBg,
        handleToggleCoverColorBg,
        isDaylight,
        toggleDaylightMode,
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        enableSmartAtmosphere,
        disableVisualizerVignette,
        handleSetVisualizerBackgroundMode,
        handleSetInteractive3dSceneTuning,
        handleToggleEnableSmartAtmosphere,
        handleToggleDisableVisualizerVignette,
        homeLayoutStyle,
        setActiveGridViewCollection,
        navigateDirectHome,
        onApplyLyricColorPreset,
    } = core;

    const homeModel = useMemo(() => buildHomeModel({
        playSong,
        navigateToPlayer,
        refreshUserData,
        user,
        playlists,
        cloudPlaylist,
        favoriteAlbums,
        isFavoriteAlbumsLoading,
        favoriteAlbumsLoadFailed,
        currentSong,
        playerState,
        handlePlaylistSelect,
        handleAlbumSelect: handleUnifiedAlbumSelect,
        handleArtistSelect: handleUnifiedArtistSelect,
        focusedPlaylistIndex,
        setFocusedPlaylistIndex,
        focusedFavoriteAlbumIndex,
        setFocusedFavoriteAlbumIndex,
        focusedRadioIndex,
        setFocusedRadioIndex,
        openSettings,
        navigateToSearch,
        openLocalAlbumByName,
        openLocalArtistByName,
        localSongs,
        localPlaylists,
        onRefreshLocalSongs,
        onPlayLocalSong,
        onAddLocalSongToQueue: handleLocalQueueAdd,
        localMusicState,
        setLocalMusicState,
        onMatchSong: handleHomeMatchSong,
        onPlayNavidromeSong,
        onAddNavidromeSongsToQueue: addNavidromeSongsToQueue,
        onMatchNavidromeSong,
        navidromeFocusedAlbumIndex,
        setNavidromeFocusedAlbumIndex,
        pendingNavidromeSelection,
        setPendingNavidromeSelection,
        stageSource,
        activePlaybackContext,
        openStagePlayer,
        stageStatus,
        setStageStatus,
        leaveStagePlayback,
        clearStagePlaybackSession,
        clearPersistedStagePlaybackCache,
        loadStageSessionIntoPlayback,
        theme,
        navidromeEnabled,
        playAll: playOnlineQueueFromStart,
        addAllToQueue: addNeteaseSongsToQueue,
        addSongToQueue: addNeteaseSongToQueue,
    }), [
        activePlaybackContext,
        addNavidromeSongsToQueue,
        addNeteaseSongsToQueue,
        addNeteaseSongToQueue,
        clearPersistedStagePlaybackCache,
        clearStagePlaybackSession,
        cloudPlaylist,
        currentSong,
        favoriteAlbums,
        favoriteAlbumsLoadFailed,
        focusedFavoriteAlbumIndex,
        focusedPlaylistIndex,
        focusedRadioIndex,
        handleHomeMatchSong,
        handleLocalQueueAdd,
        handlePlaylistSelect,
        handleUnifiedAlbumSelect,
        handleUnifiedArtistSelect,
        isFavoriteAlbumsLoading,
        leaveStagePlayback,
        loadStageSessionIntoPlayback,
        localMusicState,
        localPlaylists,
        localSongs,
        navigateToPlayer,
        navigateToSearch,
        navidromeEnabled,
        navidromeFocusedAlbumIndex,
        onMatchNavidromeSong,
        onPlayLocalSong,
        onPlayNavidromeSong,
        onRefreshLocalSongs,
        openLocalAlbumByName,
        openLocalArtistByName,
        openSettings,
        openStagePlayer,
        pendingNavidromeSelection,
        playOnlineQueueFromStart,
        playSong,
        playerState,
        playlists,
        refreshUserData,
        setFocusedFavoriteAlbumIndex,
        setFocusedPlaylistIndex,
        setFocusedRadioIndex,
        setLocalMusicState,
        setNavidromeFocusedAlbumIndex,
        setPendingNavidromeSelection,
        setStageStatus,
        stageSource,
        stageStatus,
        theme,
        user,
    ]);

    const playerPanelModel = useMemo(() => buildPlayerPanelModel({
        isPanelOpen,
        setIsPanelOpen,
        panelTab,
        setPanelTab,
        navigateToHome,
        handleDirectHomeFromPanel,
        coverUrl,
        currentSong,
        handleAlbumSelect: handlePlayerPanelAlbumSelect,
        handleArtistSelect: handlePlayerPanelArtistSelect,
        effectiveLoopMode,
        toggleLoop,
        handleLike,
        isLiked: (() => {
            if (!currentSong) return false;
            if (isLocalPlaybackSong(currentSong)) {
                return isLocalSongLiked(currentSong);
            }
            if (isNavidromePlaybackSong(currentSong)) {
                const navidromeSong = resolveNavidromePlaybackCarrier(currentSong);
                return navidromeSong ? starredNavidromeSongIds.has(navidromeSong.navidromeData.id) : false;
            }
            return likedSongIds.has(currentSong.id);
        })(),
        generateAITheme: generateCurrentSongTheme,
        activateSmartTheme: activateCurrentSmartTheme,
        isGeneratingTheme,
        hasLyrics: !!lyrics,
        canGenerateAITheme,
        theme,
        setTheme,
        bgMode,
        handleBgModeChange,
        hasCustomTheme,
        themeSourceModel,
        handleResetTheme,
        defaultTheme: DEFAULT_THEME,
        daylightTheme: DAYLIGHT_THEME,
        visualizerMode,
        handleSetVisualizerMode,
        handleManualMatchOnline,
        handleUpdateLocalLyrics,
        handleChangeLyricsSource,
        onlineLyricsState: currentSong?.onlineLyricsState ?? null,
        handleImportOnlineLyrics,
        handleChangeOnlineLyricsSource,
        handleMatchOnlineLyrics,
        handleClearOnlineLyricsState,
        lyricTimelineOffsetMs,
        handleLyricTimelineOffsetChange: setLyricTimelineOffsetMs,
        replayGainMode,
        handleChangeReplayGainMode,
        isFmMode,
        handleFmTrash,
        handleNextTrack,
        handlePrevTrack,
        playerState,
        togglePlay,
        volume,
        isMuted,
        handlePreviewVolume,
        handleSetVolume,
        handleToggleMute,
        showOpenPanelCloseButton,
        hideToggleButton: isPlayerChromeHidden || shouldHidePlayerRightPanelButton,
        activePlaybackContext,
        isNowPlayingControlDisabled,
        openSettings,
        openCommandPalette: commandPalette.open,
        isCommandPaletteOpen: commandPalette.isOpen,
        playQueue,
        playSong,
        queueScrollRef,
        shuffleQueue,
        localPlaylists,
        playlists,
        saveCurrentQueueAsLocalPlaylist,
        addCurrentSongToLocalPlaylist,
        createCurrentLocalPlaylist,
        addCurrentSongToNeteasePlaylist,
        addCurrentSongToNavidromePlaylist,
        createCurrentNavidromePlaylist,
        ...createPlayerPanelCollectionNavigation({
            homeLayoutStyle,
            currentSong,
            localSongs,
            setActiveGridViewCollection,
            navigateDirectHome,
            openCurrentLocalAlbum,
            openCurrentLocalArtist,
            openCurrentNavidromeAlbum,
            openCurrentNavidromeArtist,
        }),
        handleCopySongInfoSuccess: createCopySongInfoSuccessHandler({ setStatusMsg, t }),
        user,
        handleLogout,
        audioQuality,
        setAudioQuality,
        cacheSize,
        handleClearCache,
        handleSyncData,
        isSyncing,
        refreshUserData,
        useCoverColorBg,
        handleToggleCoverColorBg,
        isDaylight,
        handleToggleDaylight: toggleDaylightMode,
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        enableSmartAtmosphere,
        disableVisualizerVignette,
        handleSetVisualizerBackgroundMode,
        handleSetInteractive3dSceneTuning,
        handleToggleEnableSmartAtmosphere,
        handleToggleDisableVisualizerVignette,
        openAdvancedBackgroundSettings: () => openSettings('options', 'visualizer'),
        onApplyLyricColorPreset,
    }), [
        activePlaybackContext,
        addCurrentSongToLocalPlaylist,
        addCurrentSongToNavidromePlaylist,
        addCurrentSongToNeteasePlaylist,
        audioQuality,
        cacheSize,
        canGenerateAITheme,
        commandPalette.open,
        commandPalette.isOpen,
        coverUrl,
        createCurrentLocalPlaylist,
        createCurrentNavidromePlaylist,
        currentSong,
        effectiveLoopMode,
        activateCurrentSmartTheme,
        generateCurrentSongTheme,
        handleBgModeChange,
        handleChangeOnlineLyricsSource,
        handleChangeLyricsSource,
        handleClearCache,
        handleClearOnlineLyricsState,
        handleDirectHomeFromPanel,
        handleFmTrash,
        handleImportOnlineLyrics,
        handleLike,
        handleLogout,
        handleManualMatchOnline,
        handleMatchOnlineLyrics,
        handleNextTrack,
        handlePlayerPanelAlbumSelect,
        handlePlayerPanelArtistSelect,
        handlePreviewVolume,
        handlePrevTrack,
        handleResetTheme,
        handleSetVisualizerMode,
        handleSetVolume,
        handleSyncData,
        handleToggleCoverColorBg,
        handleToggleMute,
        handleToggleDisableVisualizerVignette,
        handleToggleEnableSmartAtmosphere,
        handleSetVisualizerBackgroundMode,
        handleSetInteractive3dSceneTuning,
        handleUpdateLocalLyrics,
        hasCustomTheme,
        homeLayoutStyle,
        isDaylight,
        isFmMode,
        isGeneratingTheme,
        isMuted,
        isNowPlayingControlDisabled,
        isPanelOpen,
        isPlayerChromeHidden,
        isSyncing,
        likedSongIds,
        localPlaylists,
        localSongs,
        lyrics,
        lyricTimelineOffsetMs,
        navigateDirectHome,
        navigateToHome,
        openCurrentLocalAlbum,
        openCurrentLocalArtist,
        openCurrentNavidromeAlbum,
        openCurrentNavidromeArtist,
        openSettings,
        panelTab,
        playQueue,
        playSong,
        playerState,
        playlists,
        queueScrollRef,
        refreshUserData,
        replayGainMode,
        saveCurrentQueueAsLocalPlaylist,
        setActiveGridViewCollection,
        setAudioQuality,
        setIsPanelOpen,
        setLyricTimelineOffsetMs,
        setPanelTab,
        setTheme,
        shouldHidePlayerRightPanelButton,
        showOpenPanelCloseButton,
        shuffleQueue,
        starredNavidromeSongIds,
        theme,
        themeSourceModel,
        toggleDaylightMode,
        toggleLoop,
        togglePlay,
        t,
        useCoverColorBg,
        user,
        visualizerBackgroundMode,
        interactive3dSceneTuning,
        enableSmartAtmosphere,
        disableVisualizerVignette,
        visualizerMode,
        volume,
    ]);

    return {
        homeModel,
        playerPanelModel,
    };
}
