import type { StoreApi } from 'zustand';
import { readStoredAppLanguagePreference } from '../../i18n/config';
import { readStoredSettingsChromeDaylightMode } from '../../utils/settings/settingsChromeDaylightMath';
import type { SettingsModalInitialTab, SettingsUiState } from './types';
import {
    ENABLE_BILIBILI_VIDEO_BACKGROUND_STORAGE_KEY,
    AUTO_RESYNC_DOWNLOAD_FOLDER_KEY,
    ENABLE_MEDIA_CACHE_KEY,
    ENABLE_SMART_ATMOSPHERE_STORAGE_KEY,
    HARMONY_SUBTITLE_BACKGROUND_STORAGE_KEY,
    HIDE_TASKBAR_ICON_STORAGE_KEY,
    LAST_SEEN_GUIDE_VERSION_STORAGE_KEY,
    MINIMIZE_TO_TRAY_STORAGE_KEY,
    OPEN_PLAYER_ON_LAUNCH_STORAGE_KEY,
    AUTO_PLAY_ON_LAUNCH_STORAGE_KEY,
    PLAYBACK_PRESENTATION_STORAGE_KEY,
    SHOW_HARMONY_SUBTITLE_STORAGE_KEY,
    SUBTITLE_FONT_INHERITS_LYRICS_STORAGE_KEY,
    SUBTITLE_OVERLAY_BACKGROUND_STORAGE_KEY,
    getStoredBoolean,
    parsePlaybackPresentation,
    readDefaultDaylightPreference,
    readOnboardingCompleted,
    readStoredAudioQuality,
    readStoredBackgroundOpacity,
    readStoredCadenzaTuning,
    readStoredCappellaTuning,
    readStoredCladdaghTuning,
    readStoredClassicTuning,
    readStoredDisableHomeDynamicBackground,
    readStoredFumeTuning,
    readStoredPartitaTuning,
    readStoredPendoloTuning,
    readStoredSubtitleContentMode,
    readStoredSubtitleFontFamily,
    readStoredSubtitleFontScale,
    readStoredSubtitleFontStyle,
    readStoredSubtitleOverlayOpacity,
    readStoredTiltTuning,
    readStoredVisualizerFrameRate,
    readStoredVisualizerMode,
    readStoredVisualizerOpacity,
} from './settingsPersistenceCore';
import {
    bootVisualizerBackgroundMode,
    readStoredAudioOutputDeviceId,
    readStoredCustomLyricsFont,
    readStoredGrid3dCardStyle,
    readStoredGridViewCardLayout,
    readStoredHomeLayoutStyle,
    readStoredInteractive3dSceneTuning,
    readStoredLatentBackgroundTuning,
    readStoredNomandBackgroundTuning,
    readStoredLocalBeatAnalysisMode,
    readStoredLocalBeatAnalysisPromptPolicy,
    readStoredLoopMode,
    readStoredLyricEffectPackId,
    readStoredLyricFilterPattern,
    readStoredLyricStaffAbsorbMode,
    readStoredLyricStaffMinDwellSeconds,
    readStoredLyricStaffPattern,
    readStoredLyricStaffPolicy,
    readStoredLyricFontPresetId,
    readStoredLyricWordMode,
    readStoredLyricsFontScale,
    readStoredLyricsFontStyle,
    readStoredMonetBackgroundTuning,
    readStoredMonetTuning,
    readStoredPlayerLyricsVisible,
    readStoredPreferredAlternativeLyricSource,
    readStoredQueueAddBehavior,
    readStoredUrlBackgroundList,
    readStoredUrlBackgroundSelectedId,
    readStoredVisualEffectIntensity,
    readStoredVolume,
} from './settingsPersistenceExtended';
import { readStoredGlobalLyricTimelineOffsetMs } from '../../utils/playback/globalLyricTimelineOffsetMath';
import { readStoredPreventDisplaySleepDuringPlayback } from '../../utils/settings/displaySleepSettingsMath';
import {
    readStoredStageTrackPillMode,
    readStoredStageTrackPillOnHome,
    readStoredStageTrackPillTimeoutSec,
} from '../../utils/settings/stageTrackPillSettingsMath';
import { readStoredSleepTimerHours, readStoredSleepTimerMinutes } from '../../utils/settings/sleepTimerSettingsMath';
import { readStoredDesktopLyricsYFactor } from '../../utils/desktopLyrics/desktopLyricsPlacementMath';

// src/stores/settingsUi/buildSettingsUiInitialState.ts
// Data-only initial fields for the settings UI store.

type SetState = StoreApi<SettingsUiState>['setState'];

export const buildSettingsUiInitialState = (set: SetState) => ({
    statusSetter: null,
    audioQuality: readStoredAudioQuality(),
    useCoverColorBg: getStoredBoolean('use_cover_color_bg', false),
    staticMode: getStoredBoolean('static_mode', false),
    disableHomeDynamicBackground: readStoredDisableHomeDynamicBackground(),
    enableAlternativeLyricSources: getStoredBoolean('enable_alternative_lyric_sources', true),
    autoUseBestLyric: getStoredBoolean('auto_use_best_lyric', true),
    preferredAlternativeLyricSource: readStoredPreferredAlternativeLyricSource(),
    lyricsResolveBaseUrl: typeof window !== 'undefined'
        ? (localStorage.getItem('lyra_lyrics_resolve_base_url') || '')
        : '',
    lyricsResolveApiKey: typeof window !== 'undefined'
        ? (localStorage.getItem('lyra_lyrics_resolve_api_key') || '')
        : '',
    hidePlayerTranslationSubtitle: getStoredBoolean('hide_player_translation_subtitle', false),
    showSubtitleTranslation: readStoredSubtitleContentMode() !== 'none',
    subtitleContentMode: readStoredSubtitleContentMode(),
    showHarmonySubtitle: getStoredBoolean(SHOW_HARMONY_SUBTITLE_STORAGE_KEY, true),
    harmonySubtitleBackground: getStoredBoolean(HARMONY_SUBTITLE_BACKGROUND_STORAGE_KEY, false),
    subtitleFontScale: readStoredSubtitleFontScale(),
    subtitleOverlayBackground: getStoredBoolean(SUBTITLE_OVERLAY_BACKGROUND_STORAGE_KEY, false),
    subtitleFontInheritsLyrics: getStoredBoolean(SUBTITLE_FONT_INHERITS_LYRICS_STORAGE_KEY, true),
    subtitleFontStyle: readStoredSubtitleFontStyle(),
    subtitleFontFamily: readStoredSubtitleFontFamily(),
    hidePlayerRightPanelButton: getStoredBoolean('hide_player_right_panel_button', false),
    transparentPlayerBackground: getStoredBoolean('transparent_player_background', false),
    enablePlayerPageNativeBlur: getStoredBoolean('enable_player_page_native_blur', false),
    autoHidePlayerChrome: getStoredBoolean('auto_hide_player_chrome', false),
    playbackPresentation: parsePlaybackPresentation(
        typeof localStorage !== 'undefined' ? localStorage.getItem(PLAYBACK_PRESENTATION_STORAGE_KEY) : null,
    ),
    disableVisualizerVignette: getStoredBoolean('disable_visualizer_vignette', false),
    // Opt-in beat/cinema analysis. Light cover atmosphere stays the product fallback without it.
    enableSmartAtmosphere: getStoredBoolean(ENABLE_SMART_ATMOSPHERE_STORAGE_KEY, false),
    enableBilibiliVideoBackground: getStoredBoolean(ENABLE_BILIBILI_VIDEO_BACKGROUND_STORAGE_KEY, true),
    enable3dInteractiveBackground: false,
    minimizeToTray: getStoredBoolean(MINIMIZE_TO_TRAY_STORAGE_KEY, false),
    hideTaskbarIcon: getStoredBoolean(HIDE_TASKBAR_ICON_STORAGE_KEY, false),
    openPlayerOnLaunch: getStoredBoolean(OPEN_PLAYER_ON_LAUNCH_STORAGE_KEY, false),
    autoPlayOnLaunch: getStoredBoolean(AUTO_PLAY_ON_LAUNCH_STORAGE_KEY, false),
    enableMediaCache: getStoredBoolean(ENABLE_MEDIA_CACHE_KEY, false),
    autoResyncDownloadFolder: getStoredBoolean(AUTO_RESYNC_DOWNLOAD_FOLDER_KEY, true),
    backgroundOpacity: readStoredBackgroundOpacity(),
    subtitleOverlayOpacity: readStoredSubtitleOverlayOpacity(),
    visualizerOpacity: readStoredVisualizerOpacity(),
    visualizerBackgroundMode: bootVisualizerBackgroundMode,
    urlBackgroundList: readStoredUrlBackgroundList(),
    urlBackgroundSelectedId: readStoredUrlBackgroundSelectedId(),
    visualizerFrameRate: readStoredVisualizerFrameRate(),
    isDaylight: readDefaultDaylightPreference(),
    settingsChromeDaylightMode: readStoredSettingsChromeDaylightMode(),
    visualizerMode: readStoredVisualizerMode(),
    yieldInteractive3dParticles: false,
    holdInteractive3dParticleYield: false,
    setHoldInteractive3dParticleYield: (held: boolean) => set({ holdInteractive3dParticleYield: Boolean(held) }),
    lyricWordMode: readStoredLyricWordMode(),
    lyricFontPresetId: readStoredLyricFontPresetId(),
    visualEffectIntensity: readStoredVisualEffectIntensity(),
    lyricEffectPackId: readStoredLyricEffectPackId(),
    classicTuning: readStoredClassicTuning(),
    cadenzaTuning: readStoredCadenzaTuning(),
    partitaTuning: readStoredPartitaTuning(),
    fumeTuning: readStoredFumeTuning(),
    claddaghTuning: readStoredCladdaghTuning(),
    cappellaTuning: readStoredCappellaTuning(),
    tiltTuning: readStoredTiltTuning(),
    pendoloTuning: readStoredPendoloTuning(),
    monetBackgroundTuning: readStoredMonetBackgroundTuning(),
    latentBackgroundTuning: readStoredLatentBackgroundTuning(),
    nomandBackgroundTuning: readStoredNomandBackgroundTuning(),
    interactive3dSceneTuning: readStoredInteractive3dSceneTuning(),
    monetTuning: readStoredMonetTuning(),
    storedCappellaEmojiPack: [],
    cappellaCustomEmojiImages: [],
    isLoadingCappellaCustomEmojiPack: true,
    storedCappellaAvatarPack: [],
    cappellaCustomAvatarImages: [],
    isLoadingCappellaCustomAvatarPack: true,
    storedMonetBackgroundImage: null,
    monetBackgroundImage: null,
    isLoadingMonetBackgroundImage: true,
    storedMonetPortraitImage: null,
    monetPortraitImage: null,
    isLoadingMonetPortraitImage: true,
    appLanguagePreference: readStoredAppLanguagePreference(),
    lyricsFontStyle: readStoredLyricsFontStyle(),
    lyricsFontScale: readStoredLyricsFontScale(),
    lyricsCustomFont: readStoredCustomLyricsFont(),
    lyricFilterPattern: readStoredLyricFilterPattern(),
    lyricStaffPolicy: readStoredLyricStaffPolicy(),
    lyricStaffMinDwellSeconds: readStoredLyricStaffMinDwellSeconds(),
    lyricStaffAbsorbMode: readStoredLyricStaffAbsorbMode(),
    lyricStaffPattern: readStoredLyricStaffPattern(),
    globalLyricTimelineOffsetMs: readStoredGlobalLyricTimelineOffsetMs(),
    preventDisplaySleepDuringPlayback: readStoredPreventDisplaySleepDuringPlayback(),
    stageTrackPillMode: readStoredStageTrackPillMode(),
    stageTrackPillTimeoutSec: readStoredStageTrackPillTimeoutSec(),
    stageTrackPillOnHome: readStoredStageTrackPillOnHome(),
    sleepTimerEnabled: false,
    sleepTimerHours: readStoredSleepTimerHours(),
    sleepTimerMinutes: readStoredSleepTimerMinutes(),
    sleepTimerDeadlineMs: null,
    sleepTimerActivationId: 0,
    desktopLyricsYFactor: readStoredDesktopLyricsYFactor(),
    showOpenPanelCloseButton: getStoredBoolean('show_open_panel_close_button', true),
    enableNowPlayingStage: getStoredBoolean('enable_now_playing_stage', false),
    queueAddBehavior: readStoredQueueAddBehavior(),
    localBeatAnalysisMode: readStoredLocalBeatAnalysisMode(),
    localBeatAnalysisPromptPolicy: readStoredLocalBeatAnalysisPromptPolicy(),
    audioOutputDeviceId: readStoredAudioOutputDeviceId(),
    volume: readStoredVolume(),
    isMuted: getStoredBoolean('player_is_muted', false),
    loopMode: readStoredLoopMode(),
    gridViewCardLayout: readStoredGridViewCardLayout(),
    playerLyricsVisible: readStoredPlayerLyricsVisible(),
    homeLayoutStyle: readStoredHomeLayoutStyle(),
    grid3dCardStyle: readStoredGrid3dCardStyle(),
    activeGridViewCollection: null,
    setActiveGridViewCollection: (collection: SettingsUiState['activeGridViewCollection']) => set({ activeGridViewCollection: collection }),
    isSubSettingsViewOpen: false,
    settingsModalState: {
        isOpen: false,
        initialTab: 'help' as SettingsModalInitialTab,
        initialSubview: null,
    },
    lastSeenGuideVersion: typeof window !== 'undefined' ? localStorage.getItem(LAST_SEEN_GUIDE_VERSION_STORAGE_KEY) : null,
    isUserGuideModalOpen: false,
    isShortcutsCheatSheetOpen: false,
    onboardingCompleted: readOnboardingCompleted(),
    isOnboardingOpen: false,
    isWhatsNewOpen: false,
});
